### ISSUE TITLE
Move this repository to cancerDHC?

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/ccdh-terminology-service#1]
@balhoff and I were discussing how this repository relates to http://github.com/cancerDHC/ccdhmodel, and we were wondering if it made sense to move it to http://github.com/cancerDHC since it's going to be pretty important to both CCDH Model generation as well as for setting up the Neo4J database underlying the Terminologies service.

What do you think, @jiaola?

**Comment by jiaola** [comment]
Repo moved as suggested
