### ISSUE TITLE
Update the import script to use ccdhmodel yaml as source of attribute mapping

### ISSUE THREAD

**Issue by jiaola** [cancerDHC/ccdh-terminology-service#17]
Instead of pulling the attribute information and mappings from the google sheet, get them from the ccdhmodel yaml file.

**Comment by gaurav** [comment]
I've got a bunch of code to do this in [the ccdhmodel repository](https://github.com/cancerDHC/ccdhmodel/tree/main/generators/google-sheets) -- it's under rapid development, but it has its own Pipenv, so it should be relatively easy to get this running and to extend it if you need to.

**Comment by jiaola** [comment]
Done. See c4a38f65d3e886893206b483559d5340bfa477d1
