### ISSUE TITLE
Develop a workflow for connecting the terminology and model generation systems

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#26]
Copy of: https://github.com/cancerDHC/ccdhmodel/issues/46

**Comment by jiaola** [comment]
From the terminology service side: 

* Create an action in the ccdhmodel github repo to initiate the refreshing script in the terminology service
* implement a way to call an action in the ccdhmodel github once the refreshing is done.

**Comment by joeflack4** [comment]
Been a lot of progress on this, but still needing to do a couple of things to finish it, including: (i) test server, and (ii) merging on the ccdh-model side & setting up of secrets.

**Comment by joeflack4** [comment]
Currently just waiting for a PR merge on the ccdhmodel side; will continue with this then.

**Comment by joeflack4** [comment]
This was merged already, so closing this issue now!
