### ISSUE TITLE
Fix the build errors in the github action

### ISSUE THREAD

**Issue by jiaola** [cancerDHC/ccdh-terminology-service#30]
The build is failing. See: 

https://github.com/cancerDHC/ccdh-terminology-service/runs/3019480561

============================= test session starts ==============================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/runner/work/ccdh-terminology-service/ccdh-terminology-service, configfile: pytest.ini, testpaths: tests
plugins: Faker-8.10.0, anyio-3.2.1, docker-0.10.3
collected 6 items / 3 errors / 3 selected

==================================== ERRORS ====================================
_____________ ERROR collecting tests/ccdh/importers/test_crdc_h.py _____________
ImportError while importing test module '/home/runner/work/ccdh-terminology-service/ccdh-terminology-service/tests/ccdh/importers/test_crdc_h.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/ccdh/importers/test_crdc_h.py:1: in <module>
    from ccdh.importers.crdc_h import CrdcHImporter
ccdh/importers/crdc_h.py:4: in <module>
    from linkml.loaders import yaml_loader
E   ModuleNotFoundError: No module named 'linkml.loaders'
______________ ERROR collecting tests/ccdh/mapping/test_sssom.py _______________
ImportError while importing test module '/home/runner/work/ccdh-terminology-service/ccdh-terminology-service/tests/ccdh/mapping/test_sssom.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/ccdh/mapping/test_sssom.py:1: in <module>
    from sssom.sssom_datamodel import Mapping, MappingSet
src/sssom/sssom/__init__.py:1: in <module>
    from .sssom_datamodel import Mapping, MappingSet
src/sssom/sssom/sssom_datamodel.py:13: in <module>
    from linkml.utils.curienamespace import CurieNamespace
E   ModuleNotFoundError: No module named 'linkml.utils.curienamespace'
_______________ ERROR collecting tests/tccm/test_enumeration.py ________________
ImportError while importing test module '/home/runner/work/ccdh-terminology-service/ccdh-terminology-service/tests/tccm/test_enumeration.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tccm/test_enumeration.py:2: in <module>
    from linkml.utils.compile_python import compile_python
E   ModuleNotFoundError: No module named 'linkml.utils.compile_python'
=========================== short test summary info ============================
ERROR tests/ccdh/importers/test_crdc_h.py
ERROR tests/ccdh/mapping/test_sssom.py
ERROR tests/tccm/test_enumeration.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 16.19s ==============================

**Comment by joeflack4** [comment]
@jiaola I believe this has been fixed by recently importing `linkml_runtime`. I'll close this for now, but put it in review on the project board.
