### ISSUE TITLE
Import all properties of CRDC-H model and their mappings into neo4j

### ISSUE THREAD

**Issue by jiaola** [cancerDHC/ccdh-terminology-service#43]

**Comment by joeflack4** [comment]
Later: we'll need to add a new endpoint.

**Comment by joeflack4** [comment]
I think per our discussion at the DMH meeting, we are going to keep importing `exact_mappings`, but hold off on `close_mappings` and `related_mappings`? I believe these will all be merged soon by the ccdh model team.

**Comment by joeflack4** [comment]
I believe this PR addresses this issue: #47
