### ISSUE TITLE
Enum names in the CRDCH LinkML model will be changing soon

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/ccdh-terminology-service#45]
Note that enumeration names in the form `enum_CCDH_*` will change to `enum_CRDCH_*` once https://github.com/cancerDHC/ccdhmodel/pull/68 is completed and merged. You might need to update your code when that happens.

**Comment by joeflack4** [comment]
@jiaola Should we discuss?

**Comment by gaurav** [comment]
I don't remember what this issue refers to any more, but the Terminology Service seems to be working for CRDC-H model generation, so I don't think it's relevant any more. Should I go ahead and close this issue?

**Comment by joeflack4** [comment]
@gaurav Looks like reason this wasn't an issue is because the code base hadn't actually been updated in awhile. After being updated it broke.

**Comment by gaurav** [comment]
Lol

**Comment by joeflack4** [comment]
Fixed. This had to do not with any of the terminology service code itself, but it was caused by the neo4j docker container not being correctly refreshed upon new deployment.
