### ISSUE TITLE
Update sssom version

### ISSUE THREAD

**Issue by jiaola** [cancerDHC/ccdh-terminology-service#61]

**Comment by jiaola** [comment]
The server can't start because sssom imports linkml.utils.slot which is in an earlier version of linkml. 

Fix the version to 5b56269aac0f6b3e926bfb4d15811b229c33d618 which has the current linkml-runtime reference

**Comment by joeflack4** [comment]
Just referencing prior SSSOM issue for clarity. Originally I thought I had resolved this issue: https://github.com/cancerDHC/ccdh-terminology-service/issues/28 with this pr: https://github.com/cancerDHC/ccdh-terminology-service/pull/33

**Comment by joeflack4** [comment]
@jiaola I checked out `master` after this update and started a new docker container, ran importer, and checked endpoints. Looks good! Going to close.
