### ISSUE TITLE
Not found: https://raw.githubusercontent.com/cancerDHC/ccdhmodel/main/src/schema/ccdhmodel.yaml

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#77]
## Description
When importing, yaml file is not found.

This can be verified also by just trying to personally navigate to it in the browser: https://raw.githubusercontent.com/cancerDHC/ccdhmodel/main/src/schema/ccdhmodel.yaml

### A. Get the file back in that location
For that, just need to talk to the ccdhmodel team and figure out what's going on.

### B. Point to new location
We'd have to update in two locations:
<img width="968" alt="Screen Shot 2021-09-16 at 6 07 34 PM" src="https://user-images.githubusercontent.com/13045020/133692256-34b9a375-0a17-417b-a185-01cfef3aa8fa.png">

**Comment by joeflack4** [comment]
@gaurav Hey Gaurav, just going to ping you first on this. Do you know if this is an error, or has this file been moved?
@jiaola FYI

**Comment by gaurav** [comment]
Oops, yes, sorry, I didn't realize that you were accessing the model by URL! The YAML model is now at https://github.com/cancerDHC/ccdhmodel/blob/main/model/schema/crdch_model.yaml (so the raw URL you should use is https://raw.githubusercontent.com/cancerDHC/ccdhmodel/main/model/schema/crdch_model.yaml).

**Comment by joeflack4** [comment]
@gaurav Thanks so much!!

**Comment by joeflack4** [comment]
@jiaola Fixed. I committed the fix directly to master.
